# Bash-specific login settings

# Vi key bindings on command line
set -o vi

HISTFILE="${XDG_STATE_HOME}/bash_history"; export HISTFILE
HISTCONTROL=ignoreboth; export HISTCONTROL

shopt -s histappend
shopt -s checkwinsize

[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

PS1='\u@\h:\w\$ '

if [[ $TERM == xterm-color ]] || [[ $TERM == *-256color ]]
then
    if which tput >&/dev/null 2>&1 && tput setaf 1 >&/dev/null
    then
        PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
        GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
    fi
fi

if ! shopt -oq posix
then
    if [[ -e /usr/share/bash-completion/bash_completion ]]
    then
        . /usr/share/bash-completion/bash_completion
    elif [[ -e /etc/bash_completion ]]
    then
        . /etc/bash_completion
    fi
fi

SSH_ENV="${XDG_STATE_HOME}/ssh-agent.env"

start_agent() {
    mkdir -p "$(dirname "$SSH_ENV")"
    ssh-agent -s > "$SSH_ENV"
    chmod 600 "$SSH_ENV"
    . "$SSH_ENV" >/dev/null
}

agent_is_usable() {
    [ -n "$SSH_AGENT_PID" ] &&
    kill -0 "$SSH_AGENT_PID" 2>/dev/null &&
    [ -n "$SSH_AUTH_SOCK" ] &&
    [ -S "$SSH_AUTH_SOCK" ]
}

if [ -f "$SSH_ENV" ]; then
    . "$SSH_ENV" >/dev/null
fi

if ! agent_is_usable; then
    start_agent
fi

if [[ $- == *i* ]]; then
    ssh-add -l >/dev/null 2>&1

    if [ $? -eq 1 ]; then
        if [ -x ~/.config/ssh/provider ]
        then
            DISPLAY=1 SSH_ASKPASS=~/.config/ssh/provider ssh-add < /dev/null
        else
            ssh-add
        fi
    fi
fi

test -r "${XDG_CONFIG_HOME}/sh/bash_profile_local" && . "${XDG_CONFIG_HOME}/sh/bash_profile_local"
test -r "${XDG_CONFIG_HOME}/sh/bashrc" && . "${XDG_CONFIG_HOME}/sh/bashrc"
